services:
  pizzapi:
    container_name: pizzapi-container
    build:
      context: ./pizzapi
      dockerfile: Dockerfile
    ports:
      - 3001:3001

  pizzapp:
    container_name: pizzapp-container
    build:
      context: ./pizzapp
      dockerfile: Dockerfile
    ports:
      - 80:3000