services:
  pizzapi:
    container_name: pizzapi-container
    build:
      context: ./pizzapi
      dockerfile: Dockerfile
    expose:
      - 3001
    image: yvann773/pizzapi:latest

  pizzapp:
    container_name: pizzapp-container
    build:
      context: ./pizzapp
      dockerfile: Dockerfile
    expose:
      - 3000
    image: yvann773/pizzapp:latest
    depends_on:
      - pizzapi

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - pizzapp
      - pizzapi
